global:
  scrape_interval: 15s

  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'purchase_service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['purchase-service-specialitystore.up.railway.app:443']

  # - job_name: 'postgres'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9187']

  # - job_name: 'mysql'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9104']
