global:
  scrape_interval: 5s

  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: 'purchase_service'
    scrape_interval: 3s
    static_configs:
      - targets: ['purchase-service-specialitystore.up.railway.app']
    metrics_path: '/actuator/prometheus'
    scheme: 'https'

  # - job_name: 'postgres'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9187']

  # - job_name: 'mysql'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9104']

