scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['purchase-service-specialitystore.up.railway.app']
        labels:
          application: 'My Spring Boot Application'
    # scheme: 'https'

  # - job_name: 'postgres'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9187']

  # - job_name: 'mysql'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9104']

